-- Project Preflight Cloud v1 — Supabase setup
-- Run once in Supabase SQL Editor.
-- Browser clients receive NO Supabase key. The Render backend uses SUPABASE_SECRET_KEY.

create extension if not exists pgcrypto;

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  display_name text not null,
  role text not null check (role in ('admin','planner','technician')),
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists sessions_user_idx on public.sessions(user_id);
create index if not exists sessions_expiry_idx on public.sessions(expires_at);

create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  case_no text unique not null,
  source text not null default 'planner',
  customer text not null,
  city text,
  phone text,
  email text,
  type text not null,
  asset text,
  status text not null,
  score integer not null default 0,
  problem text,
  facts jsonb not null default '[]'::jsonb,
  missing jsonb not null default '[]'::jsonb,
  dispatch text,
  prep jsonb not null default '[]'::jsonb,
  assigned_to bigint references public.users(id),
  intake_seconds integer,
  version integer not null default 1,
  created_by bigint references public.users(id),
  created_at timestamptz not null default now(),
  planner_ready_at timestamptz,
  scheduled_at timestamptz,
  closed_at timestamptz,
  updated_at timestamptz not null default now(),
  manufacturer text,
  model text,
  serial_no text,
  knowledge_title text,
  knowledge_url text,
  api_targets jsonb not null default '[]'::jsonb,
  fault_category text,
  fault_confidence text,
  triage_level text,
  fault_evidence jsonb not null default '[]'::jsonb,
  service_route text,
  required_competence text,
  remote_checks jsonb not null default '[]'::jsonb,
  site_trigger text,
  prep_categories jsonb not null default '[]'::jsonb,
  escalation_path text,
  route_source_title text,
  route_source_url text,
  ftf_critical jsonb not null default '[]'::jsonb,
  ftf_gaps jsonb not null default '[]'::jsonb,
  ftf_parts jsonb not null default '[]'::jsonb,
  outcome_resolved_first_visit boolean,
  outcome_second_visit_required boolean,
  outcome_remote_resolved boolean,
  outcome_missing_info text,
  outcome_missing_material text,
  outcome_wrong_skill boolean,
  outcome_preventable boolean,
  outcome_notes text,
  outcome_planner_minutes numeric,
  outcome_recorded_at timestamptz
);
create index if not exists cases_assigned_idx on public.cases(assigned_to);
create index if not exists cases_updated_idx on public.cases(updated_at desc);
create index if not exists cases_outcome_idx on public.cases(outcome_recorded_at);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.cases(id) on delete cascade,
  body text not null,
  created_by bigint not null references public.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.attachments (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.cases(id) on delete cascade,
  filename text not null,
  storage_path text not null unique,
  content_type text,
  size_bytes bigint not null,
  created_by bigint references public.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit (
  id bigint generated by default as identity primary key,
  case_id bigint references public.cases(id) on delete cascade,
  user_id bigint references public.users(id),
  action text not null,
  detail text,
  created_at timestamptz not null default now()
);

create table if not exists public.pilots (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date not null,
  baseline_planner_minutes numeric,
  baseline_first_time_fix_pct numeric,
  baseline_second_visit_pct numeric,
  baseline_remote_resolved_pct numeric,
  target_planner_minutes numeric,
  target_first_time_fix_pct numeric,
  target_second_visit_pct numeric,
  target_remote_resolved_pct numeric,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pilot_snapshots (
  id bigint generated by default as identity primary key,
  pilot_id bigint not null references public.pilots(id) on delete cascade,
  snapshot_date date not null,
  outcomes integer not null,
  avg_planner_minutes numeric,
  first_time_fix_pct numeric,
  second_visit_pct numeric,
  remote_resolved_pct numeric,
  preventable_second_visit_pct numeric,
  measured_planner_value_eur numeric,
  estimated_remote_value_eur numeric,
  avoidable_waste_eur numeric,
  unique(pilot_id,snapshot_date)
);

-- Defense in depth: browser roles get no access. Only server-side secret/service role.
alter table public.settings enable row level security;
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.cases enable row level security;
alter table public.notes enable row level security;
alter table public.attachments enable row level security;
alter table public.audit enable row level security;
alter table public.pilots enable row level security;
alter table public.pilot_snapshots enable row level security;

revoke all on table public.settings,public.users,public.sessions,public.cases,public.notes,public.attachments,public.audit,public.pilots,public.pilot_snapshots from anon, authenticated;
grant usage on schema public to service_role;
grant all on table public.settings,public.users,public.sessions,public.cases,public.notes,public.attachments,public.audit,public.pilots,public.pilot_snapshots to service_role;
grant usage, select on all sequences in schema public to service_role;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant usage, select on sequences to service_role;

-- Private Storage bucket. Server secret key performs Storage operations.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values (
  'preflight-attachments',
  'preflight-attachments',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp','application/pdf']
)
on conflict (id) do update set
  public=false,
  file_size_limit=5242880,
  allowed_mime_types=excluded.allowed_mime_types;

-- There are intentionally no anon/authenticated Storage policies.
-- The trusted backend uses a Supabase secret/service key and bypasses RLS.
